ci:
  autofix_prs: false

repos:
- repo: https://github.com/dnephin/pre-commit-golang
  rev: v0.5.1
  hooks:
    - id: go-fmt
      exclude: ^vendor
    - id: go-vet
      exclude: ^vendor
    - id: go-mod-tidy
    - id: go-mod-vendor

- repo: local
  hooks:
    - id: make-build
      name: make-build
      language: system
      entry: make
      args: ['build']

- repo: https://github.com/golangci/golangci-lint
  rev: v1.53.3
  hooks:
    - id: golangci-lint

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
    - id: check-added-large-files
    - id: fix-byte-order-marker
    - id: check-case-conflict
    - id: check-executables-have-shebangs
      exclude: ^vendor
    - id: check-shebang-scripts-are-executable
      exclude: ^vendor
    - id: check-merge-conflict
    - id: check-symlinks
    - id: destroyed-symlinks
    - id: check-yaml
      args: [-m]
    - id: check-json
    - id: detect-private-key
    - id: end-of-file-fixer
      exclude: ^vendor
    - id: trailing-whitespace
      exclude: ^vendor
